### ISSUE TITLE
The user '' is not authorized to access this resource - even when token has full access

### ISSUE THREAD

**Issue by RoxanaKovaci** [coffeegist/bob-the-builder#4]
Have you ever encounter the below error even when the token in the config has Full Access to the pipelines?
![image](https://user-images.githubusercontent.com/86514837/166142239-934dd756-0154-46e2-8ed1-ff46ab77b5e4.png)

**Comment by coffeegist** [comment]
Hmm I have not, can you share more info about your setup? I think a *REDACTED* version of your bob.config file and your job file could help (be sure to scrub any private details please)

**Comment by RoxanaKovaci** [comment]
Thanks for your reply.
I think I managed to trace it back to multiple service / github connections to the Azure pipelines back-end. Still haven't figured it out why it works for some pipelines but for others it doesn't. However, it doesn't seem to be anything to do with this projects python scripts so will close off the issue.
Thank you for this project, very handy and useful.
